// web/src/components/merchant/create-deal/BountyQRCodeDisplay.tsx
import { QrCode, Download, Info, Copy, Check } from 'lucide-react';
import { Button } from '@/components/common/Button';
import { motion } from 'framer-motion';
import { useState } from 'react';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';

interface BountyQRCodeDisplayProps {
  qrCodeData?: string | null; // The QR code data from backend (e.g., "BOUNTY:123:456:timestamp:signature")
  dealId?: number; // Deal ID for generating QR code URL
  merchantName?: string;
  showInfo?: boolean;
  size?: 'sm' | 'md' | 'lg';
}

/**
 * Generates QR code image URL from data
 * Uses QR Server API (free service)
 */
const generateQRCodeImageUrl = (data: string, size: number = 200): string => {
  return `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&data=${encodeURIComponent(data)}`;
};

/**
 * Component to display bounty QR code for verification
 * Customers scan this QR code when redeeming the deal to verify they brought friends
 */
export const BountyQRCodeDisplay = ({
  qrCodeData,
  dealId,
  merchantName = 'Merchant',
  showInfo = true,
  size = 'md',
}: BountyQRCodeDisplayProps) => {
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);

  // If no QR code data but we have dealId, we can generate a placeholder
  // In production, QR code will be generated by backend after deal creation
  const displayData = qrCodeData || (dealId ? `BOUNTY:${dealId}:pending` : null);
  
  if (!displayData) {
    return (
      <div className="rounded-lg border border-neutral-200 bg-neutral-50 p-4 text-center">
        <p className="text-sm text-neutral-600">
          QR code will be generated after deal is published
        </p>
      </div>
    );
  }

  const qrCodeUrl = generateQRCodeImageUrl(displayData, size === 'sm' ? 150 : size === 'lg' ? 300 : 200);
  const sizeClasses = {
    sm: 'h-32 w-32',
    md: 'h-40 w-40',
    lg: 'h-64 w-64',
  };

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = qrCodeUrl;
    link.download = `bounty-qr-code-${merchantName.replace(/\s+/g, '-').toLowerCase()}.png`;
    link.click();
    toast({
      title: 'QR Code Downloaded',
      description: 'QR code has been saved to your downloads',
    });
  };

  const handleCopyData = async () => {
    try {
      await navigator.clipboard.writeText(displayData);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      toast({
        title: 'QR Code Data Copied',
        description: 'QR code data has been copied to clipboard',
      });
    } catch (err) {
      console.error('Failed to copy:', err);
      toast({
        title: 'Copy Failed',
        description: 'Could not copy QR code data',
        variant: 'destructive',
      });
    }
  };

  return (
    <div className="space-y-4">
      <div className="text-center">
        <div className="flex items-center justify-center gap-2 mb-3">
          <QrCode className="h-5 w-5 text-brand-primary-600" />
          <h3 className="text-lg font-semibold text-neutral-900">Bounty Verification QR Code</h3>
        </div>
        
        <div className={cn(
          "mx-auto rounded-lg border-2 border-neutral-200 bg-white p-3 shadow-sm",
          sizeClasses[size]
        )}>
          <img
            src={qrCodeUrl}
            alt="Bounty QR Code"
            className="h-full w-full object-contain"
          />
        </div>

        {showInfo && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="mt-4 rounded-lg border border-blue-200 bg-blue-50 p-3 text-left"
          >
            <div className="flex items-start gap-2">
              <Info className="h-4 w-4 text-blue-600 mt-0.5 flex-shrink-0" />
              <div className="text-sm text-blue-700">
                <p className="font-medium mb-1">How it works:</p>
                <ul className="list-disc list-inside space-y-1 text-xs">
                  <li>Customers scan this QR code when redeeming the deal</li>
                  <li>QR code verifies they brought the required number of friends</li>
                  <li>Bounty rewards are automatically calculated and credited</li>
                  <li>Print or display this QR code at your location</li>
                </ul>
              </div>
            </div>
          </motion.div>
        )}

        <div className="mt-4 flex flex-col sm:flex-row gap-2 justify-center">
          <Button
            variant="secondary"
            size="sm"
            onClick={handleDownload}
            className="flex items-center gap-2"
          >
            <Download className="h-4 w-4" />
            Download QR Code
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopyData}
            className="flex items-center gap-2"
          >
            {copied ? (
              <>
                <Check className="h-4 w-4" />
                Copied!
              </>
            ) : (
              <>
                <Copy className="h-4 w-4" />
                Copy Data
              </>
            )}
          </Button>
        </div>

        {qrCodeData && (
          <div className="mt-3 rounded-lg bg-neutral-50 p-2">
            <p className="text-xs text-neutral-500 mb-1">QR Code Data:</p>
            <p className="text-xs font-mono text-neutral-700 break-all">
              {displayData}
            </p>
          </div>
        )}
      </div>
    </div>
  );
};

