-- CreateEnum
CREATE TYPE "DealCategory" AS ENUM ('FOOD_AND_BEVERAGE', 'RETAIL', 'ENTERTAINMENT', 'HEALTH_AND_FITNESS', 'BEAUTY_AND_SPA', 'AUTOMOTIVE', 'TRAVEL', 'EDUCATION', 'TECHNOLOGY', 'HOME_AND_GARDEN', 'OTHER');

-- AlterTable
ALTER TABLE "Deal" ADD COLUMN     "category" "DealCategory" NOT NULL DEFAULT 'OTHER';
